Intel realsense GRPC server
viamrobotics/camera-servers pull request #15
Opened 2022-09-21 02:46 UTC by bhaney

First pass at a GRPC server for the intel realsense. 
- Creates two cameras, color and depth, one for each stream type
- The pointcloud generator is the same for each camera
- GetProperties also returns the intrinsics and such

I was able to get the server to stream the color and depth channel from the grpc server. Here is a creepy stream of the office at night:

![movie](https://user-images.githubusercontent.com/8298653/191402663-dc04aab9-a1df-485e-bead-fed471a44716.gif)

2022-09-21 15:55 UTC, JohnN193 requested changes
noticed this error when looking at the camera stream `got different MIME type than what was asked for	{"sent": "image/vnd.viam.rgba", "received": "image/jpeg"}`, seemed to have a similar error when requesting pngs with the slam service

2022-09-21 15:55 UTC, JohnN193 commented on grpc.make
> +pull-api: bufsetup pull-api.sh
now that we are public we should be able to just use `buf` instead of this

2022-09-21 15:55 UTC, JohnN193 commented on intelrealsenseGRPC.cpp
> +        cfg.enable_stream(RS2_STREAM_DEPTH);
[q] very possible this is out of scope for a first iteration, but would it be possible to include framewidth/height as an optional arg to the binary? where they would be used [like this](https://github.com/viamrobotics/ORB_SLAM3/blob/master/initialAttempt/record_realsense.cc#L182)

2022-09-21 19:11 UTC, tessavitabile requested changes
Looks good! I'm excited to see this happening :) A few comments, and also some high level questions:

- Is the plan to replace the existing camera servers with gRPC servers? If the answer is yes, and we expect to do that soon, then I think it's okay to temporarily have some code duplication. However, if we expect both sets of servers to hang around for awhile, we should probably refactor to avoid the duplication.
- What do you think about adding more test coverage for this repo (not in this PR, but in the near-term)? We could add C++ unit tests for the repo and integration tests with rdk, similar to what we're doing for slam. Since this work would benefit multiple teams, we could discuss how to distribute testing work among teams.

2022-09-21 19:11 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +    builder.AddListeningPort("0.0.0.0:8085", grpc::InsecureServerCredentials());
Currently the camera servers run on port 8181. Do we want to keep this the same?

2022-09-21 19:11 UTC, tessavitabile commented on rs-pcl-color.cpp
> +/***********************************************************
Do we need to check any license requirements, now that this is a public repo?

2022-09-21 19:23 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +    std::vector<std::shared_ptr<CameraOutput>> cameras;
I filed https://viam.atlassian.net/browse/DATA-468 to fix this for the existing camera servers.

2022-09-21 19:36 UTC, bhaney commented on grpc.make
> +pull-api: bufsetup pull-api.sh
there is a `make buf` command as well

2022-09-21 19:47 UTC, bhaney commented on rs-pcl-color.cpp
> +/***********************************************************
I got the code from an example directory in the RealSense git repo, which is under apache2 
https://github.com/IntelRealSense/librealsense/tree/master/wrappers/pcl/pcl-color
I left the authorship header, but got rid of the main() function. I don't know if getting rid of the main() function is considered a "major" change, but I can put the notification of that in the text of the header.

2022-09-21 19:48 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +    builder.AddListeningPort("0.0.0.0:8085", grpc::InsecureServerCredentials());
I think I will allow the port to be set from an argument into main

2022-09-21 19:51 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +               } else { // return png by default
JPEG is lossy encoded, and would destroy relevant depth info. 
I wanted JPEG for color though, because PNG encoding is the slowest you could do. 
I didn't decide to put RAW as the default, because a browser would not be able to decode and display the image.

2022-09-21 20:02 UTC, JohnN193 commented on grpc.make
> +pull-api: bufsetup pull-api.sh
yeah exactly, pull-api should no longer be needed

2022-09-21 20:07 UTC, JohnN193 commented on grpc.make
> +pull-api: bufsetup pull-api.sh
since we went public you no longer need a secrets key to use `make buf`, so we should no longer have a pull-api target

2022-09-21 20:24 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +        CameraState::get()->cameras.push_back(0);
it was from essentially just wrapping the intelrealserver code with a GRPC interface-- I will change it so that the GRPC code only accesses one camera.

2022-09-21 20:42 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +                   cv::imencode(".jpg", data->colorframe, chbuf);
nice catch!

2022-09-21 20:49 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +class CameraOutput {
To be honest, I just wanted some practice on writing GRPC servers, and decided I would make the intelrealsense server a GRPC server! In terms of _how_ we want to take care of camera servers, that's an open question... there doesn't seem to be much of a difference to me between a HTTP server and a GRPC server for cameras. 

On one hand, if we are making a registry of camera servers people can use, it seems like GRPC is the way VIAM does things, so we should write GRPC servers. On the other hand, GRPC servers are always added as remotes, and remotes cannot be added as dependencies in the robot config. At least with the HTTP servers, you can build them as camera components in the robot config, and add them as dependencies to other components.

2022-09-21 22:35 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +class CameraOutput {
changed the names, and also got rid of camera state-- so this file is self-contained and doesn't depend on the other cameraserver files

2022-09-21 22:35 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +    bool ready;
done

2022-09-21 22:36 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +    std::vector<std::shared_ptr<CameraOutput>> cameras;
added mutex to the thread to protect the data

2022-09-21 22:40 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +                output->colorframe = cv::Mat();
added checks for empty data in the GRPC methods

2022-09-21 23:42 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +        cfg.enable_stream(RS2_STREAM_DEPTH);
added command line arguments to the grpc server so you can set port number and resolution

2022-09-21 23:43 UTC, bhaney commented on grpc.make
> +pull-api: bufsetup pull-api.sh
got rid of pull-api

2022-09-21 23:43 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +            std::shared_ptr<CameraOutput> output(new CameraOutput());
done

2022-09-21 23:43 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +    builder.AddListeningPort("0.0.0.0:8085", grpc::InsecureServerCredentials());
added command line arguments to the grpc server so you can set port number and resolution

2022-09-22 03:17 UTC, bhaney commented
Rewrote the GRPC server so it doesn't use the forever-looping thread anymore.

2022-09-22 14:16 UTC, tessavitabile commented on rs-pcl-color.cpp
> +/***********************************************************
Sounds good! Do you know if there's someone we should be asking licensing questions to?

2022-09-22 14:18 UTC, bhaney commented on rs-pcl-color.cpp
> +/***********************************************************
My go-to person has been Maxim

2022-09-22 14:38 UTC, tessavitabile reviewed
This approach definitely resolves the concurrency issue, but I would be a little concerned about performance. I assume the existing camera servers are written the way they are because getting the image from the underlying camera can be an expensive operation, so we want to always have an image ready when someone requests one. Did you do any performance testing for this approach yet?

2022-09-22 14:38 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +// #include <grpcpp/ext/proto_server_reflection_plugin.h>
[nit] remove

2022-09-22 14:38 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +               std::cout << "Exception while starting pipeline for realsense camera: " << e.what() << std::endl;
Should we instead allow this exception to bubble up?

2022-09-22 14:38 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +           else {
[nit] `else` shouldn't be needed here, due to the exit on line 117.

2022-09-22 14:38 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +                  return grpc::Status(grpc::StatusCode::UNAVAILABLE, "no data in this image");
This error return should go in the `catch` on line 158. There's no guarantee that `colorframe` will be empty if an exception occurs (we explicitly set it to empty in intelrealserver).

2022-09-22 14:38 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +                  return grpc::Status(grpc::StatusCode::UNAVAILABLE, "no data in this image");
Same here, this error return should go in the `catch` on line 196.

2022-09-22 14:38 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +               std::cout << "Exception while constructing pointcloud: " << e.what() << std::endl;
Error return here?

2022-09-22 14:38 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +           }
[nit] Make sure to run `make format` before merging.

2022-09-22 14:41 UTC, bhaney commented
> This approach definitely resolves the concurrency issue, but I would be a little concerned about performance. I assume the existing camera servers are written the way they are because getting the image from the underlying camera can be an expensive operation, so we want to always have an image ready when someone requests one. Did you do any performance testing for this approach yet?

My plan today is to test out speed- if it doesnt work well in terms of speed i'll move back to the background loop

2022-09-22 16:01 UTC, JohnN193 approved these changes
LGTM, just one little nit

2022-09-22 19:04 UTC, bhaney commented
@jeremyhyde-viam  FYI

2022-09-23 12:22 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +               } else { // return jpeg by default
done - do a substring search for the MIME types which should catch "lazy"

2022-09-23 12:22 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +// #include <grpcpp/ext/proto_server_reflection_plugin.h>
done

2022-09-23 12:22 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +           }
done

2022-09-23 12:22 UTC, bhaney commented on grpc.make
> +GRPCDIR=./api/grpc/cpp/gen
done

2022-09-23 14:01 UTC, JohnN193 commented on README.md
> +* [gRPC](https://github.com/viamrobotics/rdk/tree/main/grpc/cpp)
[nit] have this point to api

2022-09-23 14:44 UTC, tessavitabile requested changes
Nice work reusing CameraState! I'm curious about any performance results you have.

2022-09-23 14:44 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +                response->set_mime_type("image/png");
Do you want to set the requested mime type here, like you do for jpeg?

2022-09-23 14:44 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +                /* currently dont support raw 16bit RGBA inputs
Do you want to create a TODO with a ticket for this?

2022-09-23 14:44 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +    } else {
This `else` shouldn't be needed, due to the exit on line 325.

2022-09-23 14:52 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +                           (reqMimeType.find("image/vnd.viam.rgba") !=
Right now, the request type when using APP is `vnd.viam.rgba+lazy` (and you can't change it, it seems), so you won't be able to display a stream from remote cameras in the CONTROL tab  if you have it return an error :/ which I why I have it return jpeg or png for now.

2022-09-23 14:55 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +                /* currently dont support raw 16bit RGBA inputs
yes I will make a ticket for this

2022-09-23 14:55 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +                response->set_mime_type("image/png");
whoops good catch!

2022-09-23 15:05 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +                      << e.what() << std::endl;
I think I'll just put a `continue` - is that enough, or do you think it would be useful to do something like "after 20 continue counts, stop the server?"

2022-09-23 15:12 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +                      << e.what() << std::endl;
`continue` sounds fine

2022-09-23 16:01 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +                /* currently dont support raw 16bit RGBA inputs
https://viam.atlassian.net/browse/RSDK-683

2022-09-23 16:47 UTC, bhaney commented
I was getting annoyed by the constant line breaks in the C++ code, so changed the column width to be a bit longer. It changed all the other cpp files in the directory, but the only ones I've actually changed are 

cameraserver.cpp
intelrealsenseGRPC.cpp

Also made the ticket for the raw RGBA mime type (+lazy is also affected by the bug)
https://viam.atlassian.net/browse/RSDK-683

2022-09-23 20:22 UTC, bhaney commented
Removed the GetPointCloud implementation as it was taking too long

2022-09-23 20:25 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +        return grpc::Status(grpc::StatusCode::UNIMPLEMENTED, "GetPointCloud unmiplemented");
removed implementation for GetPointCloud as it slowed things down from 35 ms to 500 ms

2022-09-23 20:35 UTC, JohnN193 commented on intelrealsenseGRPC.cpp
> +        return grpc::Status(grpc::StatusCode::UNIMPLEMENTED, "GetPointCloud unmiplemented");
Would there be a way to move the pointcloud construction into GetPointCloud?

2022-09-23 20:36 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +        return grpc::Status(grpc::StatusCode::UNIMPLEMENTED, "GetPointCloud unmiplemented");
I need the full rs2::frame information from color and depth frames in order to do it -- so it would require importing realsense2 into cameraserver.cpp and saving the full rs2::frame rather than the cv::Mat of the data

2022-09-23 20:40 UTC, JohnN193 commented on intelrealsenseGRPC.cpp
> +    ::grpc::Status GetProperties(ServerContext* context, const GetPropertiesRequest* request,
would you want to include something for extrinsics? sorta just remembered I set [this](https://github.com/viamrobotics/ORB_SLAM3/blob/master/initialAttempt/record_realsense.cc#L314) up at one point, not sure how much more work would be needed to get it into the format we use

2022-09-23 20:40 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +        return grpc::Status(grpc::StatusCode::UNIMPLEMENTED, "GetPointCloud unmiplemented");
Or I could change CameraState in order to take in you own custom CameraOutput class, and defined an IntelCameraOutput class that saves the rs2::frames so that it keeps that code out of cameraserver.cpp

2022-09-23 20:41 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +    ::grpc::Status GetProperties(ServerContext* context, const GetPropertiesRequest* request,
extrinsics are currently not in the proto API, and they only make sense for systems of cameras, rather than individual cameras. There should probably be another way to store information about a system of cameras.

2022-09-23 21:00 UTC, JohnN193 commented on intelrealsenseGRPC.cpp
> +    ::grpc::Status GetProperties(ServerContext* context, const GetPropertiesRequest* request,
ah yeah I used the wrong word again, meant distortion parameters

2022-09-23 21:02 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +    ::grpc::Status GetProperties(ServerContext* context, const GetPropertiesRequest* request,
oh good idea! it should work! I'll add them

2022-09-23 21:06 UTC, JohnN193 commented on intelrealsenseGRPC.cpp
> +        return grpc::Status(grpc::StatusCode::UNIMPLEMENTED, "GetPointCloud unmiplemented");
\Initial thought was making the camera thread a member of `CameraServiceImpl`, then copy the frames into something that GetPointCloud has access to, and lock the copies whenever a call to GetPointCloud happens

2022-09-26 13:21 UTC, tessavitabile approved these changes
LGTM mod comments. Nice work!

2022-09-26 13:21 UTC, tessavitabile commented on intelrealsenseGRPC.cpp
> +        std::shared_ptr<CameraOutput> output(new CameraOutput());
make_shared

2022-09-26 13:21 UTC, tessavitabile commented on cameraserver.h
> +class Vertex {
Do you want to remove this class?

2022-09-26 14:17 UTC, bhaney commented on cameraserver.h
> +    std::vector<Vertex> points;
yea since I'm not using it anymore I'll remove them

2022-09-26 15:21 UTC, bhaney commented on intelrealsenseGRPC.cpp
> +    ::grpc::Status GetProperties(ServerContext* context, const GetPropertiesRequest* request,
done

2022-09-26 15:24 UTC, bhaney commented on cameraserver.h
> +class Vertex {
done

2022-09-26 15:26 UTC, merged