09222022 Intelrealserver Improvements
viamrobotics/camera-servers pull request #17
Opened 2022-09-22 21:01 UTC by jeremyhyde-viam

intelrealserver has shown multiple errors which results in the server crashing. These include:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error occured during execution of the processing block! See the log for more info
Aborted
```

```
terminate called after throwing an instance of 'rs2::error'
  what():  Frame didn't arrive within 15000
Aborted
```

```
Segmentation fault
```

The processing block error was solved using a try except statement and the 15000 error  has not been seen since the change over to try_wait_for_frame. This change allows a boolean to be returned which if false, causes the loop to skip over the rest of the frame manipulation in that loop. Both changes result in a more stable server.

The seg faulting issue has yet to be handled due to its rare occurrence but is associated with the connection to the device:
`libusb: debug [libusb_get_device_descriptor]`. When this occurrence a restart of the intelrealserver will solve the problem but that is still not ideal.

2022-09-22 21:29 UTC, JohnN193 approved these changes
LGTM, just some small questions

2022-09-22 21:29 UTC, JohnN193 commented on intelrealserver.cpp
> +            auto succ = p.try_wait_for_frames(&frames, 1000);
[q] what is the 1000? can we make it a variable?

2022-09-22 21:29 UTC, JohnN193 commented on intelrealserver.cpp
> +                DEBUG("Failed to get frame, skipping...");
[q] should this have a cout log too? not sure if we would see DEBUG in rdk logs(or how to get it to show up for that matter)

2022-09-23 14:18 UTC, tessavitabile requested changes
Nice work finding these issues! One small comment. Also make sure to rebase/merge, so that you get the concurrency fix.

2022-09-23 14:18 UTC, tessavitabile commented on intelrealserver.cpp
> +                continue;
If this happens on the first loop, then we need to avoid setting `CameraState::get()->ready` to true, in order to avoid a null pointer dereference when trying to access the camera output.

2022-09-23 14:18 UTC, tessavitabile commented on intelrealserver.cpp
> +                continue;
Same here

2022-09-23 16:54 UTC, jeremyhyde-viam commented on intelrealserver.cpp
> +            auto succ = p.try_wait_for_frames(&frames, 1000);
1000 is a one second time out when getting new frames. Predominantly since the frame data is queued this operation takes 0 ms, this just ensures that after one it gives up on getting that particular frame. 

I will change it to be a variable located at the top of the file. In the future if we ever consider adding in optional arguments, we can make this configurable

2022-09-23 16:56 UTC, jeremyhyde-viam commented on intelrealserver.cpp
> +                DEBUG("Failed to get frame, skipping...");
Up for debate, this occurs irregularly and almost never twice in a row so I figured it would more so clutter up the logs since if it does occur, it is fixed by the next time an image is called. However, I am happy to make this a cout if that is on the concensus.

2022-09-23 17:14 UTC, jeremyhyde-viam commented on intelrealserver.cpp
> +                DEBUG("Failed to get frame, skipping...");
I think for now I will go with your suggestion of cout that way we'll have at least more data on when this occurs and how this affects ongoing rdk processes. In the future we can remove it if we do indeed feel like it's uselessly cluttering up the logs.

2022-09-23 17:22 UTC, jeremyhyde-viam commented on intelrealserver.cpp
> +                continue;
Spoke about offline, will be introduce a check for all cameras to have returned a frame before the camera state is readied. In the future we could move towards a vector for the ready variable to address each camera individually if that is desirable.

2022-09-23 17:22 UTC, jeremyhyde-viam commented on intelrealserver.cpp
> +                continue;
See previous comment

2022-09-23 18:46 UTC, tessavitabile approved these changes
LGTM

2022-09-23 19:27 UTC, bhaney approved these changes
Nice! LGTM

2022-09-23 19:27 UTC, bhaney commented on intelrealserver.cpp
> +    auto ready = true;
this should start FALSE before the loop begins

2022-09-23 19:28 UTC, bhaney commented on intelrealserver.cpp
> +    auto ready = true;
ah never mind, you use this to set the CameraState ready - ignore this comment

2022-09-23 21:36 UTC, merged