Add Z16 depth and scale from RS2 SDK
viamrobotics/camera-servers pull request #25
Opened 2023-02-15 01:33 UTC by bhaney

2023-02-15 01:35 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    unsigned result = lodepng_encode_memory(&encoded, &encoded_size, data, width, height, LCT_GREY, 16);
Need to use lodepng for depth because 16-bit grayscale is necessary for accurate depth maps.

2023-02-15 01:36 UTC, bhaney commented on intel_realsense_grpc.cpp
> +	    encodeDepthPNGToResponse(response, (const unsigned char*)latestDepthFrame->data(), this->props.depth.width,
only return PNGs for depth cameras

2023-02-15 01:36 UTC, bhaney commented on intel_realsense_grpc.cpp
> +        const uint timeoutMillis = 2000;
Matt pointed out that for 1080p, the server running on a raspberry pi would ever so often the limit of 1000ms

2023-02-15 01:37 UTC, bhaney commented on intel_realsense_grpc.cpp
> -            auto depthFrame = frames.get_depth_frame();
request the color and depth frame as close as possible in time to each other.

2023-02-15 14:44 UTC, edaniels requested changes
Done with first pass. Tested this compiling fine on x86+macos-arm

2023-02-15 14:44 UTC, edaniels commented on intel_realsense_grpc.cpp
> +    float pix2mm_depth_scale = 1.0;
```suggestion
    float depthScaleMm = 1.0;
```

let's try to use camel case in our code since we use that in most other places.

2023-02-15 14:44 UTC, edaniels commented on intel_realsense_grpc.cpp
> +    float depth_pix2mm;
```suggestion
    float depthScaleMm;
```

2023-02-15 14:44 UTC, edaniels commented on intel_realsense_grpc.cpp
> +        cerr << "[GetImage]  failed to encode PNG" << endl;
```suggestion
        cerr << "[GetImage]  failed to encode depth PNG" << endl;
```

2023-02-15 14:44 UTC, edaniels commented on intel_realsense_grpc.cpp
> +        cout << "[GetImage]  PNG encode:      " << duration.count() << "ms\n";
```suggestion
        cout << "[GetImage]  depth PNG encode:      " << duration.count() << "ms\n";
```

2023-02-15 14:44 UTC, edaniels commented on intel_realsense_grpc.cpp
> +    unsigned char* encoded = 0;
[major] you need to free this data after setting the response data. This isn't a vector like the other code has which won't be RAIId

2023-02-15 14:44 UTC, edaniels commented on intel_realsense_grpc.cpp
> +        const uint timeoutMillis = 2000;
This won't really end up mattering because of the removal of the loop sleep limiter. The try will just print out an error. I'd suggest adding the "could not get frames" into a DEBUG block so that we don't always print it.

2023-02-15 14:44 UTC, edaniels commented on intel_realsense_grpc.cpp
> -            auto depthFrame = frames.get_depth_frame();
I would change this part back with respect to time because it the frameset that rs2 returns is already synchronized. It doesn't matter when you call its accessors as long as you have the frameset.

2023-02-15 14:44 UTC, edaniels commented on intel_realsense_grpc.cpp
> -            // NOTE(erd): this is fast enough in -O3 (1920x1080 -> ~15ms) but could probably be
I would leave this note.

2023-02-15 14:44 UTC, edaniels commented on intel_realsense_grpc.cpp
> +    float pix2mm_depth_scale = 1.0;
I'd also use zero or NAN since it's not a valid value if depth is disabled.

2023-02-15 17:00 UTC, tessavitabile commented
Removed myself from reviewers, since I'm not planning to do a thorough review. Just for context, what was the problem with the previous grayscale encoding?

2023-02-15 18:25 UTC, bhaney commented
> Removed myself from reviewers, since I'm not planning to do a thorough review. Just for context, what was the problem with the previous grayscale encoding?

Depth image was being encoded as an RGB image, 8-bits per channel. Big thing was that while the image looked like a grayscale depth image, there was not a way for RDK to turn that image into depth information, and so point cloud generation failed.

1. each pixel value represented 1 mm (or 0.25 mm) of distance. 8 bits only allows 256, only allowing encodings of distances up to 25.6 cm (or 6.4 cm). 16bit channels all encoding up to 65 meters.
2. Also, RGB image structs do not have a valid conversion function to depth info in RDK. So trying to make a pointcloud would result in the error `do not know how to turn image.RGBA into DepthMap`. image.Gray16 is necessary for RDK to extract the depth information.

2023-02-15 19:43 UTC, tessavitabile commented
Thank you! I can't remember if the SLAM team ever got orblsam working with intelrealgrpcserver. I think there may have been other issues, so I'm not sure whether we encountered parsing of depth pngs. Since intelrealserver doesn't exist anymore, the SLAM team will need to make sure we can use intelrealgrpcserver with orbslam.

2023-02-16 21:59 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    float pix2mm_depth_scale = 1.0;
done

2023-02-16 21:59 UTC, bhaney commented on intel_realsense_grpc.cpp
> +        cerr << "[GetImage]  failed to encode PNG" << endl;
done

2023-02-16 21:59 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    unsigned char* encoded = 0;
free'd after setting the response, it's been so long since I've had to free my own memory

2023-02-16 21:59 UTC, bhaney commented on intel_realsense_grpc.cpp
> -            // NOTE(erd): this is fast enough in -O3 (1920x1080 -> ~15ms) but could probably be
done

2023-02-16 22:03 UTC, edaniels commented on intel_realsense_grpc.cpp
> +        return grpc::Status(grpc::StatusCode::INTERNAL, "failed to encode depth PNG");
need to free here too

2023-02-16 22:03 UTC, edaniels approved these changes
LGTM after one more change

2023-02-17 21:12 UTC, merged