RAW color and depth endpoint
viamrobotics/camera-servers pull request #29
Opened 2023-02-21 22:50 UTC by bhaney

Tested raw requests from the GRPC server using the python SDK, and got an **avg FPS of  44.65** for the 640x480 Depth images.  It might be able to be faster - I feel like I probably didn't use memcpy in the most efficient way.

Right now, we don't have a way to convert Raw Depth images in python to PIL images, this will be taken care of with https://viam.atlassian.net/browse/RSDK-1623

The Raw Color image is actually pretty slow, at 19 FPS, I suspect because I have to insert the Alpha channel into the stream (the intel realsense only has the RGB channels). But it does copy the bytes correctly:
![tmpfh0ft0jg](https://user-images.githubusercontent.com/8298653/220476279-49998bff-261f-44ae-a860-94ec9459f0ef.jpg)

2023-02-21 23:00 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    }
This seems like a pretty inefficient way to add the alpha channel to the color bytes - maybe there could be another type called `vnd.viam.rgb`

2023-02-21 23:02 UTC, bhaney commented on intel_realsense_grpc.cpp
> +}
I made this function because if you just feed in the width and height into memcpy with `&height` the bytes get inserted in backwards for some reason -- it makes the width and height huge.

2023-02-21 23:03 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    offset += heightByteCount;
I don't know if this is the best way of making sure we attach the header, width, and height to the returned raw bytes.

2023-02-21 23:03 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    std::memcpy(rawBuf + offset, data, pixelByteCount);
I don't know if this is the best way of making sure we attach the header, width, and height to the returned raw bytes.

2023-02-21 23:06 UTC, bhaney commented on intel_realsense_grpc.cpp
> +const uint32_t rgbaMagicNumber = 1094862674; // the utf-8 binary encoding for "RGBA", big-endian
this actually encodes "ABGR", but for some reason, when inserted `&rgbaMagicNumber` into memcpy, it copied the bytes in backwards. so I wrote the magic number as ""ABGR" so that it gets copied correctly to the buffer as "RGBA"

2023-02-22 14:17 UTC, edaniels requested changes

2023-02-22 14:17 UTC, edaniels commented on intel_realsense_grpc.cpp
> +const uint32_t rgbaMagicNumber = 1094862674; // the utf-8 binary encoding for "RGBA", big-endian
That's probably correct but keep in mind this happens due to endianness. You want to send big endian over the wire. It may be easier to represent this as a C-string

2023-02-22 14:17 UTC, edaniels commented on intel_realsense_grpc.cpp
> +    size_t magicByteCount = sizeof(rgbaMagicNumber);
we should just have this sizeof be a constant. we know how many bytes it is

2023-02-22 14:17 UTC, edaniels commented on intel_realsense_grpc.cpp
> +    size_t widthByteCount = sizeof(width);
I think all of these are basically consts in advance. we don't want to really rely on sizeof when we know the format ourselves. this can technically change in a different compiler and we don't want that risk

2023-02-22 14:17 UTC, edaniels commented on intel_realsense_grpc.cpp
> +    intToByteArray(width, widthBytes);
I think you can avoid doing this conversion loop here and instead do all your copying into the rawBuf you are creating below.

2023-02-22 14:17 UTC, edaniels commented on intel_realsense_grpc.cpp
> +    size_t pixelByteCount = 2*width*height;
I feel like this can be merged into the other code somewhat

2023-02-22 14:17 UTC, edaniels commented on intel_realsense_grpc.cpp
> +    for (int i = 0; i < width*height; i++) {
have you done timings and/or profiling in this code to understand what's the slowest part? I'm curious if there's any big wins we can get

2023-02-22 14:40 UTC, tessavitabile requested changes

2023-02-22 14:40 UTC, tessavitabile commented on intel_realsense_grpc.cpp
> +tuple<unsigned char*, long unsigned int, bool> encodeJPEG(const unsigned char* data,
any changes to this function?

2023-02-22 14:40 UTC, tessavitabile commented on intel_realsense_grpc.cpp
> +grpc::Status encodeJPEGToResponse(GetImageResponse* response, const unsigned char* data,
any changes to this function?

2023-02-22 14:40 UTC, tessavitabile commented on intel_realsense_grpc.cpp
> +    size_t widthByteCount = sizeof(width);
agreed. can we also have a static check to make sure the sizes for these types are what we expect?

2023-02-22 14:40 UTC, tessavitabile commented on intel_realsense_grpc.cpp
> +	        } else {
make sure to format

2023-02-22 14:40 UTC, tessavitabile commented on intel_realsense_grpc.cpp
> +}
There might be ways to do this using the standard library, such as std::reverse_copy: https://stackoverflow.com/questions/5585532/c-int-to-byte-array.

2023-02-22 14:42 UTC, edaniels commented on intel_realsense_grpc.cpp
> +    size_t widthByteCount = sizeof(width);
yes or we can use things like uint32_t and such to always know its underlying size_t

2023-02-22 22:14 UTC, bhaney commented on intel_realsense_grpc.cpp
> +#include <arpa/inet.h>
need the htonl function in order to ensure big-endian encoding.

2023-02-22 22:15 UTC, bhaney commented on intel_realsense_grpc.cpp
> +
library doesn't have 64bit htonl, so made the 64bit version out the the 32bit function

2023-02-22 22:16 UTC, bhaney commented on intel_realsense_grpc.cpp
> +const size_t depthHeightByteCount = 8;  // number of bytes used to represent depth image height
Made consts of all the numbers. Also using the magicNumber as they would be  in big-endian encoding, and will convert all ints to be big-endian

2023-02-22 22:17 UTC, bhaney commented on intel_realsense_grpc.cpp
> +        magicNumberToEncode = magicNumber << 32 | magicNumber;
in order to make `encodeRAW` work for both types, need to treat 32-bit and 64-bit headers differently.

2023-02-22 22:37 UTC, bhaney commented on intel_realsense_grpc.cpp
> +tuple<unsigned char*, long unsigned int, bool> encodeJPEG(const unsigned char* data,
no, the color encoding for JPEG stays the same

2023-02-22 22:38 UTC, bhaney commented on intel_realsense_grpc.cpp
> +grpc::Status encodeJPEGToResponse(GetImageResponse* response, const unsigned char* data,
same here, color encoding to JPEG can stay the same

2023-02-22 22:40 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    intToByteArray(width, widthBytes);
yes, did this - just had to use the htonl function to ensure everything is always big-endian.

2023-02-22 22:42 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    size_t pixelByteCount = 2*width*height;
I tried to do this here: https://github.com/bhaney/camera-servers/blob/3a50818b1c4bd230038f8ec8dc749542b874505f/intel_realsense_grpc.cpp#L84

but it was annoying having to treat 32bit and 64bit numbers differently, especially because I was stuffing everything into 64bit numbers, and then having to be careful how htonll changed the shape of the bytes

2023-02-22 22:43 UTC, bhaney commented on intel_realsense_grpc.cpp
> +	        } else {
done

2023-02-22 22:43 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    size_t pixelByteCount = 2*width*height;
So I think I'm gonna keep the two encodeToRAW functions separate

2023-02-22 22:44 UTC, bhaney commented on intel_realsense_grpc.cpp
> +        magicNumberToEncode = magicNumber << 32 | magicNumber;
JK! Not doing this any more.

2023-02-22 22:44 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    for (int i = 0; i < width*height; i++) {
Gonna do this tomorrow

2023-02-22 22:45 UTC, bhaney commented on intel_realsense_grpc.cpp
> +}
ended up using the htonl function

2023-02-22 22:45 UTC, bhaney commented on intel_realsense_grpc.cpp
> +const uint32_t rgbaMagicNumber = 1094862674; // the utf-8 binary encoding for "RGBA", big-endian
using htonl to ensure big-endian

2023-02-22 22:46 UTC, bhaney commented on intel_realsense_grpc.cpp
> +    size_t magicByteCount = sizeof(rgbaMagicNumber);
done

2023-02-22 22:50 UTC, bhaney commented on intel_realsense_grpc.cpp
> +const size_t depthHeightByteCount = 8;  // number of bytes used to represent depth image height
gonna use sizeof(uint_32) and sizeof(uint_64)

2023-02-23 02:56 UTC, edaniels commented on intel_realsense_grpc.cpp
> +#include <arpa/inet.h>
just make sure this compiles on macos.

2023-02-23 02:57 UTC, edaniels approved these changes

2023-02-23 14:27 UTC, tessavitabile approved these changes
LGTM mod comment

2023-02-23 14:27 UTC, tessavitabile commented on intel_realsense_grpc.cpp
> +                                         this->props.color.width, this->props.color.height);
This should be depth instead of color.

2023-02-23 16:03 UTC, bhaney commented on intel_realsense_grpc.cpp
> +                                         this->props.color.width, this->props.color.height);
good catch!!!!

2023-02-23 17:18 UTC, bhaney commented on intel_realsense_grpc.cpp
> +#include <arpa/inet.h>
Turns out I need to upgrade to macOS 13

2023-02-23 21:24 UTC, bhaney commented on intel_realsense_grpc.cpp
> +#include <arpa/inet.h>
I'm even getting to the point where the protobuf stuff is correct - I'm compiling on macOS but getting weird errors
```
Undefined symbols for architecture arm64:
  "google::protobuf::internal::InternalMetadata::~InternalMetadata()", referenced from:
      google::protobuf::MessageLite::~MessageLite() in robot-b18dd7.o
      google::protobuf::MessageLite::~MessageLite() in common-0c589a.o
      google::protobuf::MessageLite::~MessageLite() in camera-b49fa7.o
      google::protobuf::MessageLite::~MessageLite() in httpbody-3e2f78.o
      google::protobuf::MessageLite::~MessageLite() in http-c48037.o
ld: symbol(s) not found for architecture arm64
```

2023-02-24 16:38 UTC, bhaney commented on intel_realsense_grpc.cpp
> +#include <arpa/inet.h>
Got it to work! It compiles

2023-02-24 16:39 UTC, merged